export const ActionTypes = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_WISHLIST: "SET_WISHLIST",
  SET_CART: "SET_CART",
  SET_SUB_CATEGORIES: "SET_SUB_CATEGORIES",
  UPDATE_CART: "UPDATE_CART",
  UPDATE_WISHLIST_CART: "UPDATE_WISHLIST_CART",
  RESET_STORE: "RESET_STORE",
};
